version:  '3.9'

services:
    db:
        image: postgres:11.12-alpine
        cap_add:
            - SYS_NICE
        environment:
            POSTGRES_DB: messenger_app
            POSTGRES_USER: app_user
            POSTGRES_PASSWORD: app_pass
        volumes:
            - './bin/postgresql/:/var/lib/postgresql/data'
        networks:
            - messenger_symfony_network

    test-db:
        image: postgres:11.12-alpine
        cap_add:
            - SYS_NICE
        # volumes are not persisted in test db
        ports:
            - '8070:5432' # notice different OUT port than in default database
        networks:
            - messenger_symfony_network

    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
            network: host
        expose:
            - '9000'
        depends_on:
            - db
        volumes:
            - './app/:/var/www/app:cached'
        networks:
            - messenger_symfony_network

    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: messenger_rabbitmq
        restart: unless-stopped
        environment:
            - RABBITMQ_ERLANG_COOKIE=7ead507151fc4461b9f45c1161384a04
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
            - RABBITMQ_DEFAULT_VHOST=/
        volumes:
            - ./rabbitmq/data/:/var/lib/rabbitmq/
        ports:
            - 15444:15672
            - 5699:5672
        networks:
            - messenger_symfony_network

    nginx:
        build: docker/nginx
        depends_on:
            - db
            - php
        volumes:
            - './app/:/var/www/app:cached'
            - './logs/nginx:/var/log/nginx'
        networks:
                - messenger_symfony_network

networks:
    messenger_symfony_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.65.67.0/24