version: '3.4'
#@see https://docs.docker.com/compose/compose-file/compose-file-v3/
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:
  php:
    build:
      context: ./docker/php/build
      dockerfile: Dockerfile
    container_name: messenger_symfony_${APP_ENV}_php
    restart: unless-stopped
    volumes:
      - composer:/root/.composer/cache
      - ./:/app
    logging: *default-logging
  db:
    image: mysql:5.7
    restart: always
    container_name: messenger_symfony_${APP_ENV}_db
    environment:
      MYSQL_DATABASE: '${DOCKER_MYSQL_DATABASE}'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: '${DOCKER_MYSQL_USER}'
      # You can use whatever password you like
      MYSQL_PASSWORD: '${DOCKER_MYSQL_PASSWORD}'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '${DOCKER_MYSQL_ROOT_PASSWORD}'
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
    logging: *default-logging

  nginx:
    build: ./docker/nginx/build
    image: nginx
    container_name: messenger_symfony_${APP_ENV}_nginx
    restart: unless-stopped
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./docker/nginx/config:/etc/nginx/conf.d:ro
      - ./:/app
    logging: *default-logging

volumes:
  composer:
