framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        failure_transport: failed
        transports:
            # https://symfony.com/doc/current/messenger.html#transports
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    delay: 500
            async_priority_high:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                        default_publish_routing_key: high
                    queues:
                        messages_high:
                            binding_keys: [high]




            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
        routing:
            # Route your messages to the transports
            'App\Message\Command\AddPonkaToImage': async_priority_high
            'App\Message\Event\ImagePostDeletedEvent': async
#            'App\Message\Command\DeleteImagePost': async

        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: true
                middleware:
                    - App\Middleware\AuditMiddleware
            event.bus:
                default_middleware: allow_no_handlers
                middleware:
                    - App\Middleware\AuditMiddleware
            query.bus: ~
